### ISSUE TITLE
stevetarver.github.io/_posts/2016-11-22-nexus-in-docker.md

### ISSUE THREAD

**Issue by tallandtree** [stevetarver/stevetarver.github.io#1]
Hi,
My apologies upfront as I found no other good way to contact you about this blog entry besides creating an issue. Hope you won't mind. I'm currently evaluating Nexus 3 OSS against Artifactory Pro. You mentioned in your post the following:

> Check your repository retention policies. Ensure that you trim releases to an acceptable retention period and latest images to only one.

But as far as I can see, you cannot set any retention policies except for maven snapshot repositories in the scheduled cleanup task. How did you accomplish this? Did you write the retention policies in a Groovy script?
Thanks!

**Comment by steventarver** [comment]
Mariska, 

There is still no good way to do this in Nexus. This feels like a pretty big miss for any group that uses CI. You will quickly burn through a disk when you move past the POC stage - we built 250 images in 3 days while just developing our CI/CD/CD pipeline. 

There are several open tickets around this area - this one looks like it could be part of the solution: https://issues.sonatype.org/browse/NEXUS-11435. 

Since writing that article, we have moved on to writing a home grown version to more precisely serve our Kubernetes needs so I haven't kept up on the progress in Nexus. I did notice that the first comment in this issue https://issues.sonatype.org/browse/NEXUS-9293 references a way to manage images via api: https://github.com/andrey-pohilko/registry-cli.

Glad my article could move you along a little bit - Good luck on your product review.

(closing issues as purpose was to ask a question)
